### ISSUE TITLE
enhancement: toCamelCase() convert space to  camelCase

### ISSUE THREAD

**Issue by Soecka** [EasyWebApp/web-utility#8]
In toCamelCase, I cann't convert to 'asa sasa' to 'asaSasa'
[data.ts:32](https://github.com/EasyWebApp/web-utility/blob/f656501/source/data.ts#L32)
maybe we can polish the pattern of the regExp
```typescript
 return raw.replace(/^[a-z]|-[a-z]|\s+[a-z]/g, (match, offset)

```

**Comment by TechQuery** [comment]
fixed by 9db7a03
