### ISSUE TITLE
enhancement: toHyphenCase() convert space to camelCase

### ISSUE THREAD

**Issue by Soecka** [EasyWebApp/web-utility#9]
In toHyphenCase, I cann't convert to 'socia media' to 'socia-media'
[data.ts:32](https://github.com/EasyWebApp/web-utility/blob/75dbf47/source/data.ts#L29)
maybe we can polish the pattern of the regExp

```typescript
function toHyphenCase(raw:string) {
  return raw.replace(
      /[A-Z]+|[^A-Za-z][A-Za-z]/g,
      (match, offset) => `${offset ? '-' : ''}${(match[1]||match[0]).toLowerCase()}`
  );
}
```

**Comment by TechQuery** [comment]
A pull request is welcomed.
